language: python

python:
  - "2.7"

install:
  - sudo apt-get install gcc
  - sudo apt-get install libpoppler-glib-dev python-gtk2
  - sudo apt-get install python-gobject-dev python-cairo-dev
  - sudo apt-get install python-gobject python-gobject-2
  - python setup.py sdist
  - pip install pycairo==1.8.8 --allow-unverified pycairo --allow-external pycairo
  - pip install dist/*
  - pip install -r requirements-dev.txt

script:
  - flake8 pdfcomparator tests
  - python setup.py test
